eureka:
  instance:
   prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true     
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-81039795.okta.com/oauth2/default
    audience: api://default
